/*
 * Copyright (c) 2018 NOMANA-IT and/or its affiliates.
 * All rights reserved. Use is subject to license terms.
 *
 * @author fblettner
 */
package Frames;

import custom.resources.Resource;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import custom.resources.Template;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.simpleframework.xml.Serializer;
import org.simpleframework.xml.core.Persister;

   class propertiesFilter extends javax.swing.filechooser.FileFilter {
        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".properties");
        }
        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "Text documents (*.properties)";
        }
    } 

/**
 *
 * @author fblettner
 */
public class ManageConfig extends javax.swing.JFrame {

    private String paramConfig;
    
    /**
     * Creates new form ManageConfig
     */
    public ManageConfig() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOpenConfig = new javax.swing.JFileChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bOpenFile = new javax.swing.JButton();
        bClose = new javax.swing.JButton();
        bAddTemplate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jOpenConfig.setFileFilter(new propertiesFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Template Name", "Description"
            }
        ) {
            public boolean isCellEditable(int row, int column){return false;}
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        }
    );
    jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jTable1.setShowGrid(true);
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane2.setViewportView(jTable1);

    bOpenFile.setText("Open Configuration");
    bOpenFile.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bOpenFileActionPerformed(evt);
        }
    });

    bClose.setText("Close");
    bClose.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bCloseActionPerformed(evt);
        }
    });

    bAddTemplate.setText("Add Template");
    bAddTemplate.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bAddTemplateActionPerformed(evt);
        }
    });

    jButton1.setText("Copy Template");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jButton2.setText("Remove Template");
    jButton2.setToolTipText("");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane2)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(bOpenFile)
            .addGap(26, 26, 26)
            .addComponent(bAddTemplate)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton2)
            .addGap(34, 34, 34)
            .addComponent(bClose)
            .addContainerGap(66, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(17, 17, 17)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bOpenFile)
                .addComponent(bClose)
                .addComponent(bAddTemplate)
                .addComponent(jButton1)
                .addComponent(jButton2))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_bCloseActionPerformed

    private void bOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOpenFileActionPerformed
       jOpenConfig.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int returnVal = jOpenConfig.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jOpenConfig.getSelectedFile();
        try {
            paramConfig = file.getAbsolutePath();
            Serializer serializer = new Persister();
            Template templates = serializer.read(Template.class, file);
            
            List<Resource> test = templates.getAllTemplates();
            
            for (int i = 0; i < test.size(); i++) {
                Object[] row = { test.get(i).getName(), test.get(i).getProperty("description")};

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(model);

            jTable1.setRowSorter(sorter);
            model.addRow(row);
            }
                                
            
        } catch (IOException ex) {
          System.out.println("problem accessing file"+file.getAbsolutePath());
        }   catch (Exception ex) {
                Logger.getLogger(ManageConfig.class.getName()).log(Level.SEVERE, null, ex);
            }
    } else {
        System.out.println("File access cancelled by user.");
    }
    }//GEN-LAST:event_bOpenFileActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2){
              TableModel tm = jTable1.getModel();
              int row=jTable1.getSelectedRow();
              
              if (jTable1.getRowSorter()!=null) {
                    row = jTable1.getRowSorter().convertRowIndexToModel(row);
                }
              String template = tm.getValueAt(row,0).toString();

              if (template.equals("global")){
                 ManageGlobal ManageGlobal = new ManageGlobal();
                  try {
                      ManageGlobal.GlobalInit(template,paramConfig);
                      
                  } catch (Exception ex) {
                      Logger.getLogger(ManageConfig.class.getName()).log(Level.SEVERE, null, ex);
                  }
                ManageGlobal.setVisible(true);                 
              }else {
                ManageTemplate ManageTemplate = new ManageTemplate();
                  try {
                      ManageTemplate.TemplateInit(template,paramConfig);
                      
                  } catch (Exception ex) {
                      Logger.getLogger(ManageConfig.class.getName()).log(Level.SEVERE, null, ex);
                  }
                ManageTemplate.setVisible(true); 
              }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void bAddTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddTemplateActionPerformed
        ManageTemplate ManageTemplate = new ManageTemplate();
        ManageTemplate.setVisible(true); 

    }//GEN-LAST:event_bAddTemplateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageConfig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddTemplate;
    private javax.swing.JButton bClose;
    private javax.swing.JButton bOpenFile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jOpenConfig;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
